version: '3.7'

services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/dream_tiny/pipeline_conf.json'
    environment:
      WAIT_HOSTS: "sentseg:8011,ranking-based-response-selector:8002,factoid-qa:8071,dff-dream-persona-chatgpt-prompted-skill:8137,dff-dream-faq-prompted-skill:8170"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1000}
      HIGH_PRIORITY_INTENTS: 1
      RESTRICTION_FOR_SENSITIVE_CASE: 1
      ALWAYS_TURN_ON_ALL_SKILLS: 0
      LANGUAGE: EN
      FALLBACK_FILE: fallbacks_dream_en.json

  ranking-based-response-selector:
    env_file: .env
    build:
      context: .
      dockerfile: ./response_selectors/ranking_based_response_selector/Dockerfile
      args:
        SERVICE_PORT: 8002
        SERVICE_NAME: response_selector
        LANGUAGE: EN
        SENTENCE_RANKER_ANNOTATION_NAME: sentence_ranker
        SENTENCE_RANKER_SERVICE_URL: http://sentence-ranker:8128/respond
        SENTENCE_RANKER_TIMEOUT: 3
        N_UTTERANCES_CONTEXT: 5
        FILTER_TOXIC_OR_BADLISTED: 1
        FALLBACK_FILE: fallbacks_dream_en.json
    command: flask run -h 0.0.0.0 -p 8002
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M

  sentseg:
    env_file: .env
    build:
      context: ./annotators/SentSeg/
    command: flask run -h 0.0.0.0 -p 8011
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1.5G

  factoid-qa:
    env_file: .env
    build:
      context: .
      dockerfile: ./skills/factoid_qa/Dockerfile
      args:
        SERVICE_PORT: 8071
        SERVICE_NAME: factoid_qa
    command: flask run -h 0.0.0.0 -p 8071
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  dff-dream-persona-chatgpt-prompted-skill:
    env_file:
      - .env
      
    build:
      context: .
      dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
      args:
        SERVICE_PORT: 8137
        SERVICE_NAME: dff_dream_persona_prompted_skill
        PROMPT_FILE: common/prompts/dream_persona.json
        GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
        GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
        GENERATIVE_TIMEOUT: 120
        N_UTTERANCES_CONTEXT: 7
        ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

  dff-dream-faq-prompted-skill:
    env_file:
      - .env

    build:
      context: .
      dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
      args:
        SERVICE_PORT: 8170
        SERVICE_NAME: dff_dream_faq_prompted_skill
        PROMPT_FILE: common/prompts/dream_faq.json
        GENERATIVE_SERVICE_URL: http://openai-api-chatgpt-16k:8167/respond
        GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
        GENERATIVE_TIMEOUT: 120
        N_UTTERANCES_CONTEXT: 7
        ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
